name: par-segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21.6
  - matplotlib=3.3.4
  - pandas=1.3.4
  - scipy=1.7.3
  - tensorflow=2.9.1
  - joblib=0.17.0
  - ipywidgets=7.5.1
  - scikit-learn=0.23.2
  - scikit-image=0.14.2
  - jupyter=1.0.0
  - tqdm=4.55.2
  - pip
  - pip:
      - opencv-python==4.2.0.34
      - matplotlib-polyroi==0.1.3
      - par-segmentation==0.1.7