name: par-segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.0
  - matplotlib=3.8.0
  - pandas=2.1.1
  - scipy=1.11.3
  - joblib=1.3.2
  - ipywidgets=8.1.1
  - scikit-image=0.22.0
  - jupyter=1.0.0
  - tqdm=4.66.1
  - ipympl=0.9.3
  - pip
  - pip:
      - opencv-python==4.8.1.78
      - matplotlib-polyroi==0.1.6
      - tensorflow==2.14.0
      - par-segmentation==0.1.10
